-- Canonical clean-install schema. Existing installations: php migrations/migrate.php
CREATE TABLE IF NOT EXISTS categories (
 id INTEGER PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100) NOT NULL,
 slug VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(255) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 is_admin INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS products (
 id INTEGER PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL,
 slug VARCHAR(255) NOT NULL UNIQUE,
 description TEXT NOT NULL,
 price DECIMAL(10,2) NOT NULL,
 stock INTEGER NOT NULL DEFAULT 0,
 category_id INTEGER,
 image_url VARCHAR(255),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 deleted_at TIMESTAMP NULL DEFAULT NULL,
 FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS cart_items (
 id INTEGER PRIMARY KEY AUTO_INCREMENT,
 session_id VARCHAR(255) NOT NULL,
 product_id INTEGER NOT NULL,
 quantity INTEGER NOT NULL DEFAULT 1,
 added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE (session_id, product_id),
 FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS orders (
 id INTEGER PRIMARY KEY AUTO_INCREMENT,
 user_id INTEGER,
 customer_name VARCHAR(100) NOT NULL,
 customer_email VARCHAR(255) NOT NULL,
 shipping_address TEXT NOT NULL,
 shipping_city VARCHAR(100) NOT NULL,
 shipping_country VARCHAR(100) NOT NULL,
 shipping_postal_code VARCHAR(20) NOT NULL,
 phone VARCHAR(30) NOT NULL,
 payment_method VARCHAR(50) NOT NULL DEFAULT 'cash_on_delivery',
 subtotal DECIMAL(10,2),
 shipping_amount DECIMAL(10,2),
 tax_amount DECIMAL(10,2),
 total_price DECIMAL(10,2) NOT NULL,
 status VARCHAR(50) NOT NULL DEFAULT 'pending',
 checkout_key VARCHAR(64) UNIQUE,
 cart_owner VARCHAR(255),
 order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS order_items (
 id INTEGER PRIMARY KEY AUTO_INCREMENT,
 order_id INTEGER NOT NULL,
 product_id INTEGER NOT NULL,
 product_name VARCHAR(255),
 quantity INTEGER NOT NULL,
 unit_price DECIMAL(10,2) NOT NULL,
 FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
 FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS login_attempts (
 attempt_key VARCHAR(64) PRIMARY KEY,
 attempts INTEGER NOT NULL,
 expires_at INTEGER NOT NULL
);
